# Generated by Django 3.2.8 on 2021-10-11 23:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('innovaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='emailEstudiante',
            field=models.EmailField(db_index=True, default=datetime.datetime(2021, 10, 11, 23, 27, 38, 994703, tzinfo=utc), max_length=100, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='emailEstudiante',
            field=models.EmailField(default='', max_length=100, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
