# Generated by Django 3.2.8 on 2021-10-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovaApp', '0002_auto_20211011_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
