# Generated by Django 3.2.8 on 2021-10-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovaApp', '0003_auto_20211011_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
